### ISSUE TITLE
hiding the guilds only

### ISSUE THREAD

**Issue by ryudragon98** [kosshishub/CompactGuilds-BD-plugin#2]
when hiding just the guilds and not the channels when you go to reveal the guilds and go to the top to click on dms its a little troublesome to do so as it doesnt move the guild name at the top so it makes it hard as you have to try and click below it since it cuts the very top icon for dm in half, can you make it so that when just hiding guilds it also moves the guild name when moving to reveal all hidden guilds so that i dont have to fight with trying to put my cursor in the right spot just to get to dms.

**Comment by kosshi-net** [comment]
Please write readable english and try again.

**Comment by ryudragon98** [comment]
when i go to settings and click the setting to hide guilds and leave the channels still showing i cant click on dms since the name of a server blocks part of the dm icon making it hard to go into dms

**Comment by kosshi-net** [comment]
Are you using custom themes?

**Comment by ryudragon98** [comment]
yeah im using the discord reborn theme

**Comment by kosshi-net** [comment]
The issue is that theme, tell its author to stop messing with z-indexes. It should be relatively easy to patch, just edit edit the z-index of the blocking element.

**Comment by ryudragon98** [comment]
what should the z-index be at for it to work with the plugin

**Comment by kosshi-net** [comment]
Depends if rest of the theme modifies other elements, try lowering it from where it's now.

**Comment by ryudragon98** [comment]
okay its at -1 so how far lower

**Comment by kosshi-net** [comment]
-2? Just try.

**Comment by ryudragon98** [comment]
still didnt work i still have the little problem where i have a hard time getting in to dms

**Comment by ryudragon98** [comment]
*/
/*Change the url in .app to change the background behind chat */

.app { background-image: url("https://imgur.com/RG03PyX.png") !important; background-size: cover !important; }

/*Change the url in .callout-backdrop to change the background when modal pop outs happen */

.callout-backdrop { background-color: black !important; background-image: url("https://imgur.com/RG03PyX.png") !important; -webkit-transition: 0.3s all ease; -o-transition: 0.3s all ease; -moz-transition: 0.3s all ease; transition: 0.3s all ease; background-size: cover !important; -webkit-filter: brightness(75%); }

/*Change the urls below to change the background of a profile modal pop up */

.user-popout:before {
    background-image: url("https://imgur.com/RG03PyX.png") !important;
    content: "";position: absolute;left: 0;top: 0;height: 100%;width: 100%;z-index: -1;background-position: 50% 50%;-webkit-filter: blur(3px);-webkit-transform: scale(1.05);transform: scale(1.05);}

#user-profile-modal .header:before {
    background: -webkit-linear-gradient(top, rgba(0, 0, 0, .3), rgba(0, 0, 0, 0.5)), url("https://imgur.com/RG03PyX.png") !important;
    background: linear-gradient(to bottom, rgba(0, 0, 0, .3), rgba(0, 0, 0, 0.5)), url("https://imgur.com/RG03PyX.png") !important;
    content: "";position: absolute;left: 0;top: 0;width: 100%;height: 100%;z-index: -1;background-position: 50% 50%;background-size: cover !important;-webkit-filter: blur(3px);-webkit-transform: scale(1.1);transform: scale(1.1);}

 /*


this is in the file for the theme im using with your plugin

**Comment by kosshi-net** [comment]
I don't know what you are doing but throw `.guild-header{ z-index: -2 !important; }` to custom css, and just edit the number, if still doesn't work, go bother the themes author.
