### ISSUE TITLE
Discord top bar stays on top of channel panel when it slides out

### ISSUE THREAD

**Issue by dafzor** [kosshishub/CompactGuilds-BD-plugin#3]
Discord top bar (channel name, description, mentions, notifications, etc) stays above the guild panel when it slides out as shown in the example bellow:
![example](https://cloud.githubusercontent.com/assets/1612206/24625480/0500a660-18a7-11e7-90f5-efd8a3f9abf2.png)

**Comment by kosshi-net** [comment]
Fixed, I hope. Redownload or add ``.chat div.title-wrap{z-index: 0 !important}`` to customcss.

**Comment by dafzor** [comment]
Fixed confirmed, that was super fast. Thanks

**Comment by dafzor** [comment]
Spoke too soon, opening discord in the same size has shown in the example image the issue still present. If the bar is maximized and then restored to the size shown in the image the issue is resolved.

**Comment by kosshi-net** [comment]
Ill fix that soon, for now put ```.chat div.title-wrap{z-index: 0 !important}``` to customcss, should work
(after 3 months, this is now been fixed)
