### ISSUE TITLE
An option to set deactivation width to be equal to sidebar width

### ISSUE THREAD

**Issue by Kommynct** [kosshishub/CompactGuilds-BD-plugin#7]
title pretty much says it, i really need this. No idea how to write it myself or i would've.

thank you for your time.

**Comment by kosshi-net** [comment]
If with deactivation width you mean the window width, you can just set the "Max window size to enable.." option to equal the sidebar width, 310px. I don't see any point in adding another button to already cluttered and messy ui to do something like this.
If you meant the distance from left edge your cursor needs to be to hide the sidebar, same thing with the poorly named "hide distance" option.

**Comment by Kommynct** [comment]
This issue matters with the shrink sidebar option, unless it's a bug, my sidebars size changes dynamically.

**Comment by kosshi-net** [comment]
How does it change dynamically?
