### ISSUE TITLE
Plugin has broken

### ISSUE THREAD

**Issue by ghost** [kosshishub/CompactGuilds-BD-plugin#9]
So today this plugin suddenly stopped working, i cant get the error that relates directly to the plugin anymore but i can get the errors it seems to cause. [These are the errors it causes, there isnt much variation to them. ](https://my.mixtape.moe/mvqrud.png)

EDIT: [I got the error the plugin makes and now better discord doesnt work. (enables guild hiding always)](https://my.mixtape.moe/crrkij.png)

**Comment by kosshi-net** [comment]
Are you using the newest version of the plugin?

**Comment by ghost** [comment]
yea

**Comment by kosshi-net** [comment]
Try removing the following lines in the source:
```
63	document.querySelectorAll('div[class^=container]')[9].style.position = "relative";
64	document.querySelectorAll('div[class^=container]')[9].style.top = "-20px";
173	document.querySelectorAll('div[class^=container]')[9].style.position = "";
174	document.querySelectorAll('div[class^=container]')[9].style.top = "";
```
And tell what happens

**Comment by ghost** [comment]
it work now, thanks!

**Comment by kosshi-net** [comment]
Good, but now the box under channels is slightly off screen, isn't it? I opened issue #10 for this.

**Comment by ghost** [comment]
~~yeah but i don't really care~~
wait i dont know what you mean. the only offscreen thing i see is [this](https://my.mixtape.moe/qsiuvv.png)
